services:
  db-server:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: awdrqwer12
      POSTGRES_DB: hackmx
    profiles:
      - prod

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-server
    ports:
      - "8080:8080"
    volumes:
      - cargo-cache:/usr/local/cargo
    environment:
      MODE: production
      RUST_LOG: debug
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: postgres://admin:awdrqwer12@db-server:5432/hackmx
      DATABASE_HOST: db-server

      ADMIN_DEFAULT_EMAIL: admin@hackmx.com
      ADMIN_DEFAULT_PASSWORD: awdrqwer12

      USER_SECRET_KEY: secret
      ADMIN_SECRET_KEY: secret2

      USER_COOKIE_NAME: token_page
      ADMIN_COOKIE_NAME: token_platform

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: awdrqwer12
      POSTGRES_DB: hackmx

      SMTP_HOST: smtp-mail.outlook.com
      SMTP_USERNAME: test@outlook.com
      SMTP_PASSWORD: test
      SMTP_SENDER: "HackMx <test@outlook.com>"
    profiles:
      - prod

volumes:
  db-data:
  cargo-cache:
